---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - python
  fixme:
    enabled: false
  radon:
    enabled: true
    config:
      threshold: "C"
ratings:
  paths:
  - "OpenHealthAlgorithms/**.py"
exclude_paths:
- dist/
- tests/
- venv/
- cvdrisk/
- demo.py
